source 'https://rubygems.org'

group :development, :test do
  gem 'jekyll', '~> 4.2.2'
  gem 'jekyll-seo-tag', '~> 2.7.1'
  gem 'jekyll-sitemap', '~> 1.4.0'
  gem 'wdm', '~> 0.1.1', :install_if => Gem.win_platform?
end


gem "webrick", "~> 1.7"
